-- MySQL Script generated by MySQL Workbench
-- ศ. 11 พ.ย. 2559, 08:52:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Position` (
  `position_Id` INT NOT NULL AUTO_INCREMENT,
  `position_Name` VARCHAR(45) NOT NULL,
  `salary` INT(7) NOT NULL,
  PRIMARY KEY (`position_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Staff` (
  `STAFF_ID` INT NOT NULL AUTO_INCREMENT,
  `DOB` DATE NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Lastname` VARCHAR(45) NOT NULL,
  `Area_ID` VARCHAR(45) NOT NULL,
  `position_Id` INT NOT NULL,
  PRIMARY KEY (`STAFF_ID`),
  INDEX `POSITION_ID_idx` (`position_Id` ASC),
  CONSTRAINT `POSITION_ID`
    FOREIGN KEY (`position_Id`)
    REFERENCES `mydb`.`Position` (`position_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ANIMAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ANIMAL` (
  `TYPE_ID` INT NOT NULL COMMENT '\n',
  `Area_ID` INT NOT NULL,
  `STAFF_ID` INT NULL,
  PRIMARY KEY (`TYPE_ID`),
  INDEX `STAFF_ID_idx` (`STAFF_ID` ASC),
  INDEX `AREA_ID_idx` (`Area_ID` ASC),
  CONSTRAINT `STAFF_ID`
    FOREIGN KEY (`STAFF_ID`)
    REFERENCES `mydb`.`Staff` (`STAFF_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `AREA_ID`
    FOREIGN KEY (`Area_ID`)
    REFERENCES `mydb`.`Area` (`Area_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Area` (
  `Area_ID` INT NOT NULL,
  `WIDTH` INT(10) NOT NULL,
  `STAFF_ID` INT(10) NOT NULL,
  `AREA_TYPE` VARCHAR(45) NOT NULL,
  `ANIMAL_ID` INT NOT NULL,
  PRIMARY KEY (`Area_ID`),
  INDEX `STAFF_ID_idx` (`STAFF_ID` ASC),
  INDEX `ANIMAL_ID_idx` (`ANIMAL_ID` ASC),
  CONSTRAINT `STAFF_ID`
    FOREIGN KEY (`STAFF_ID`)
    REFERENCES `mydb`.`Staff` (`STAFF_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ANIMAL_ID`
    FOREIGN KEY (`ANIMAL_ID`)
    REFERENCES `mydb`.`ANIMAL` (`TYPE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ANIMAL_INFO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ANIMAL_INFO` (
  `ANIMAL_ID` INT NOT NULL AUTO_INCREMENT,
  `TYPE_ID` VARCHAR(45) NOT NULL,
  `ANIMAL_NAME` VARCHAR(45) NOT NULL,
  `ANIMAL_STATUS` VARCHAR(45) NOT NULL,
  `ANIMAL_BIRTH` DATE NOT NULL,
  PRIMARY KEY (`ANIMAL_ID`),
  CONSTRAINT `TYPE_ID`
    FOREIGN KEY (`ANIMAL_ID`)
    REFERENCES `mydb`.`ANIMAL` (`TYPE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FOOD_ID`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FOOD_ID` (
  `FOOD_ID` INT NOT NULL AUTO_INCREMENT,
  `FOOD_NAME` VARCHAR(45) NOT NULL,
  `FOOD_PRICE` INT NOT NULL,
  `EXP` DATE NOT NULL,
  PRIMARY KEY (`FOOD_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ANIMAL_FOOD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ANIMAL_FOOD` (
  `FOOD_ID` INT NOT NULL,
  `TYPE_ID` INT NOT NULL,
  `QUANTITY` INT NOT NULL,
  `FOOD_TYPE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`FOOD_ID`),
  INDEX `TYPE_ID_idx` (`TYPE_ID` ASC),
  CONSTRAINT `FOOD_ID`
    FOREIGN KEY (`FOOD_ID`)
    REFERENCES `mydb`.`FOOD_ID` (`FOOD_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TYPE_ID`
    FOREIGN KEY (`TYPE_ID`)
    REFERENCES `mydb`.`ANIMAL` (`TYPE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TICKET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TICKET` (
  `TICKET_ID` INT NOT NULL,
  `TICKET_PRICE` INT NOT NULL,
  `TICKET_DATE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TICKET_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CUSTOMER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CUSTOMER` (
  `CUUSTOMER_NO` INT NOT NULL AUTO_INCREMENT,
  `SEX` VARCHAR(45) NOT NULL,
  `TICKET_TYPE` INT NOT NULL,
  PRIMARY KEY (`CUUSTOMER_NO`),
  INDEX `TICKET_TYPE_idx` (`TICKET_TYPE` ASC),
  CONSTRAINT `TICKET_TYPE`
    FOREIGN KEY (`TICKET_TYPE`)
    REFERENCES `mydb`.`TICKET` (`TICKET_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EARN_PAID`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EARN_PAID` (
  `LIST_NO` INT NOT NULL AUTO_INCREMENT,
  `FOOD_PRICE` INT NOT NULL,
  `TICKET_PRICE` INT NOT NULL,
  `salary` INT NOT NULL,
  PRIMARY KEY (`LIST_NO`),
  INDEX `FOOD_PRICE_idx` (`FOOD_PRICE` ASC),
  INDEX `TICKET_PRICE_idx` (`TICKET_PRICE` ASC),
  INDEX `SALARY_idx` (`salary` ASC),
  CONSTRAINT `FOOD_PRICE`
    FOREIGN KEY (`FOOD_PRICE`)
    REFERENCES `mydb`.`FOOD_ID` (`FOOD_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TICKET_PRICE`
    FOREIGN KEY (`TICKET_PRICE`)
    REFERENCES `mydb`.`TICKET` (`TICKET_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SALARY`
    FOREIGN KEY (`salary`)
    REFERENCES `mydb`.`Position` (`position_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
